using Content.Shared._Fish.Mechs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Fish.Mechs;

[GenerateTypedNameReferences]
public sealed partial class MechMedicalSleeperUiFragment : BoxContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public event Action<EntityUid>? OnEjectAction;
    public event Action<string>? OnInjectAction;

    private EntityUid? _patient;

    public MechMedicalSleeperUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        EjectButton.OnPressed += _ =>
        {
            if (_patient is { } patient)
                OnEjectAction?.Invoke(patient);
        };
    }

    public void UpdateContents(MechMedicalSleeperUiState state)
    {
        ReagentList.Clear();
        _patient = null;
        EjectButton.Disabled = true;

        if (state.Contents.Count > 0)
        {
            var ent = _entity.GetEntity(state.Contents[0]);
            _patient = ent;
            EjectButton.Disabled = false;

            var name = _entity.TryGetComponent(ent, out MetaDataComponent? meta)
                ? meta.EntityName
                : Loc.GetString("mech-sleeper-patient-unknown");

            PatientLabel.Text = Loc.GetString("mech-sleeper-patient", ("name", name));
        }
        else
        {
            PatientLabel.Text = Loc.GetString("mech-sleeper-patient-empty");
        }

        InjectHintLabel.Text = Loc.GetString("mech-sleeper-inject-hint", ("amount", state.InjectAmount));

        foreach (var reagent in state.Reagents)
        {
            var label = Loc.GetString("mech-sleeper-reagent-entry",
                ("name", reagent.DisplayName),
                ("quantity", reagent.Quantity));

            var item = ReagentList.AddItem(label);
            var reagentId = reagent.ReagentId;
            item.OnSelected += _ => OnInjectAction?.Invoke(reagentId);
        }
    }
}
