- type: job
  id: BlueShieldOfficer
  name: job-name-blueshield-officer
  description: job-description-blueshield-officer
  playTimeTracker: JobBlueShield
  requirements:
   - !type:DepartmentTimeRequirement
     department: Security
     time: 62000 # 20 hrs
   - !type:AgeRequirement
     requiredAge: 20
  startingGear: BlueShieldOfficerGear
  icon: JobIconBlueShield
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
   - Command
   - Bar
   - Service
   - Maintenance
   - Janitor
   - Theatre
   - Kitchen
   - Chapel
   - Hydroponics
   - External
   - Chemistry
   - Engineering
   - Research
   - Salvage
   - Cargo
   - Atmospherics
   - Cargo
   - Medical
   - BlueShield
  special:
   - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]

- type: startingGear
  id: BlueShieldOfficerGear
  equipment:
   shoes: ClothingShoesBootsBlueShieldFilled
   eyes: ClothingEyesGlassesBlueShield
   head: ClothingHeadHatBeretBlueShield
   outerClothing: ClothingOuterArmorBlueShield
   id: BlueShieldOfficerPDA
   ears: ClothingHeadsetBlueShield
   gloves: ClothingHandsGlovesCombat
   pocket1: BaseUplinkNTERTBlueShield
  storage:
   back:
   - HandheldBSOCrewMonitor
