- type: department
  id: FractionCoreWM
  name: department-fractioncorewm-name
  description: department-fractioncorewm-desc
  color: "#0000e3"
  roles:
  - JobCoreBase
  - JobCorePC0I5
  - JobCorePM1
  - JobCorePE1
