- type: job
  id: JobCoreBase
  name: Боевик #Республиканец - стояло у всех первым столов в словосочетании джоба
  description: Подготовленный расходник
  playTimeTracker: OverAllCoreBase
  setPreference: false
  weight: 2
  jobEntity: MobHumanCoreP0WMF5
  icon: "IconCoreBase"
  canBeAntag: false
  access:
  - AssCoreBase
  alwaysUseSpawner: true

- type: job
  id: JobCorePC0I5
  name: Лейтенант
  description: Командуюший офицер 
  playTimeTracker: OverAllCorePC0I5
  setPreference: false
  weight: 5
  jobEntity: MobHumanCorePC0I5WMF5
  #startingGear: SkeletonBiker
  icon: "IconCorePC0I5"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssCorePC0I5
  - AssCorePM1
  - AssCorePE1
  alwaysUseSpawner: true

- type: job
  id: JobCorePM1
  name: Врач
  description: Предоставляет медицинскую услугу
  playTimeTracker: OverAllCorePM1
  setPreference: false
  weight: 3
  jobEntity: MobHumanCorePM1WMF5
  icon: "IconCorePM1"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssCorePM1
  alwaysUseSpawner: true

- type: job
  id: JobCorePE1
  name: Инженер
  description: Возводит оборонительные сооружения
  playTimeTracker: OverAllCorePE1
  setPreference: false
  weight: 4
  jobEntity: MobHumanCorePE1WMF5
  icon: "IconCorePE1"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssCorePE1
  alwaysUseSpawner: true
