- type: job
  id: JobCoreBase
  name: pw-roles-republic-jobcorebase-name
  description: pw-roles-republic-jobcorebase-desc
  playTimeTracker: OverAllCoreBase
  setPreference: false
  weight: 2
  jobEntity: MobHumanCoreP0WMF5
  icon: "IconCoreBase"
  canBeAntag: false
  access:
  - AssCoreBase
  alwaysUseSpawner: true
  supervisors: job-title-republic-lieutenant


- type: job
  id: JobCorePC0I5
  name: pw-construction-republic-mobhumancorepc0i5-name
  description: pw-roles-republic-jobcorepc0i5-desc
  playTimeTracker: OverAllCorePC0I5
  setPreference: false
  weight: 5
  jobEntity: MobHumanCorePC0I5WMF5
  #startingGear: SkeletonBiker
  icon: "IconCorePC0I5"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssCorePC0I5
  - AssCorePM1
  - AssCorePE1
  alwaysUseSpawner: true
  supervisors: job-supervisors-republic-council


- type: job
  id: JobCorePM1
  name: pw-construction-republic-mobhumancorepm1-name
  description: pw-roles-republic-jobcorepm1-desc
  playTimeTracker: OverAllCorePM1
  setPreference: false
  weight: 3
  jobEntity: MobHumanCorePM1WMF5
  icon: "IconCorePM1"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssCorePM1
  alwaysUseSpawner: true
  supervisors: job-title-republic-lieutenant


- type: job
  id: JobCorePE1
  name: pw-construction-republic-mobhumancorepe1-name
  description: pw-roles-republic-jobcorepe1-desc
  playTimeTracker: OverAllCorePE1
  setPreference: false
  weight: 4
  jobEntity: MobHumanCorePE1WMF5
  icon: "IconCorePE1"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssCorePE1
  alwaysUseSpawner: true
  supervisors: job-title-republic-lieutenant
