

- type: chameleonOutfit
  id: CBURNLeaderChameleonOutfit
  job: CBURNLeader
  hasMindShield: true
  equipment:
    outerClothing: ClothingOuterHardsuitCBURNLeader
    neck: ClothingNeckScarfStripedBrown
