- type: entity
  name: mango
  parent: FoodProduceBase
  id: FoodMango
  description: Mango mango mango mango!
  components:
  - type: FlavorProfile
    flavors:
      - apple
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 14
        reagents:
        - ReagentId: Razorium
          Quantity: 10
  - type: Sprite
    sprite: Objects/Specific/Hydroponics/apple.rsi
  - type: Produce
    seedId: apple
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Razorium
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
  # - type: FoodSequenceElement
  #   entries:
  #     Burger: Apple
  #     Taco: Apple

