- type: job
  id: NanoTrasenRepresentative
  name: job-name-ntrep
  description: job-description-ntrep
  playTimeTracker: JobNanoTrasenRepresentative
  requirements:
    - !type:DiscordRoleRequirement #Fish-edit
  startingGear: NanoTrasenRepresentativeGear
  icon: JobIconNanotrasen
  joinNotifyCrew: true
  radioBold: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  #Fish-start
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  #Fish-end
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantBlueShield ]
    - !type:AddComponentSpecial
      components:
      - type: CommandStaff

- type: startingGear
  id: NanoTrasenRepresentativeGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesSunGlassesHudSkill
    head: ClothingHeadHatCapNtrep
    id: NanoTrasenRepresentativePDA
    ears: ClothingHeadsetAltCommand
    pocket1: FlippoEngravedLighter
    pocket2: PenCentcom
  storage:
    back:
    - RubberStampNtrep
    - CaneNT
    - HandheldFax #sunrise-edit
    - RubberStampVeto #sunrise-edit
