- type: gameMapPool
  id: FishMapPool
  maps:
  - FishDelta
<<<<<<< Snowboll
  - FishGate
  # - FishBarratry
  # - FishPacked
=======
  - FishMarathon
  - FishPacked
>>>>>>> master
  - FishCase
  - FishOasis
  - FishPlasma
  - FishBox
  - FishBagel
  - FishIrefit
  - FishSnowball