# НЕ ДОБАВЛЯТЬ НОВЫЕ КАРТЫ БЕЗ МОЕГО РЕВЬЮ! ~ SplikZerys

- type: gameMapPool
  id: FishMapPool
  maps:
  # Highpop 55+
  - FishDelta
  #- SunrisePlasma # Прибытие стыкуется лишь 1 доком с доступом командования. Эвак стыкуется лишь 2 доками.
  - FishBox
  - FishFland
  #- SunriseOasis # Прибытие не стыкуется. Эвак залазит в станцию.

  # Midpop 25-55
  #- SunriseMarathon # Прибытие не стыкуется. Эвак залазит в станцию.
  - FishBagel
  - FishBarratry

  # Lowpop 0-25
  - FishPacked
  #- SunriseReach # Стыкпорт прибытия не настроен под шаттл прибытия. Нет эвака

  # НЕИГРАБЕЛЬНЫЕ:
  #- SunriseRelic
  # SUNRISE-TODO: Старые-новые карты
  #- Glacier
  #- Shoukou
  #- Hammurabi
  #- Lighthouse
  #- Angle
  #- Pebble
  #- Ovni
  #- Kettle
  #- Tortuga
  #- Arena
