- type: job
  id: IAA
  name: job-name-iaa
  description: job-description-iaa
  playTimeTracker: JobIAA
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15h Sunrise-RoleTime #Fish-edit
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10h Sunrise-RoleTime #Fish-edit
  startingGear: IAAGear
  icon: "JobIconFishIAA" #Fish-edit
  supervisors: job-supervisors-magistrate
  canBeAntag: false
  displayWeight: 40
  access:
  - Command
  - Service
  - Brig
  - Maintenance
  - External
  - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: IAAGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: IAAPDA
    neck: ClothingNeckLawDepbadge #Fish-edit
    eyes: ClothingEyesGlassesHiddenSecurity #Fish-edit
    ears: ClothingHeadsetIAA
    pocket2: HyperLinkBookCorporateLaw
  inhand:
    - BriefcaseIAAFilled
