- type: accessLevel
  id: AssArmBase
  name: pw-roles-rebels-assarmbase-name


- type: accessLevel
  id: AssArmPC0I5
  name: pw-roles-rebels-assarmpc0i5-name


- type: accessLevel
  id: AssArmPM1
  name: pw-roles-rebels-assarmpm1-name


- type: accessLevel
  id: AssArmPE1
  name: pw-roles-rebels-assarmpe1-name

#имена
