using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.Dataset;
using Content.Shared.Random.Helpers;
using Content.Shared.Security;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client._Fish.SecurityHud;

[GenerateTypedNameReferences]
public sealed partial class SecurityHudCriminalStatusWindow : FancyWindow
{
    private static readonly ProtoId<LocalizedDatasetPrototype> ReasonPlaceholders = "CriminalRecordsWantedReasonPlaceholders";

    private readonly IPrototypeManager _proto;
    private readonly IRobustRandom _random;

    private uint _maxLength = 256;
    private SecurityStatus _currentStatus = SecurityStatus.None;
    private DialogWindow? _reasonDialog;
    private bool _suppressStatusEvent;

    public Action<SecurityStatus, string?>? OnStatusSelected;

    public SecurityHudCriminalStatusWindow()
    {
        RobustXamlLoader.Load(this);

        _proto = IoCManager.Resolve<IPrototypeManager>();
        _random = IoCManager.Resolve<IRobustRandom>();

        foreach (var status in Enum.GetValues<SecurityStatus>())
        {
            StatusOption.AddItem(Loc.GetString($"criminal-records-status-{status.ToString().ToLower()}"), (int) status);
        }

        StatusOption.OnItemSelected += args =>
        {
            if (_suppressStatusEvent)
                return;

            SetStatus((SecurityStatus) args.Id);
        };

        OnClose += () => _reasonDialog?.Close();
    }

    public void UpdateState(string name, string? job, SecurityStatus status, string? reason, uint maxLength)
    {
        _maxLength = maxLength;
        _currentStatus = status;
        PersonName.Text = name;
        PersonJob.Text = job ?? Loc.GetString("generic-not-available-shorthand");

        _suppressStatusEvent = true;
        StatusOption.SelectId((int) status);
        _suppressStatusEvent = false;

        UpdateStatusIcon(status);
        UpdateReasonLabel(status, reason);
    }

    private void SetStatus(SecurityStatus status)
    {
        if (status == SecurityStatus.Wanted || status == SecurityStatus.Suspected || status == SecurityStatus.Hostile)
        {
            GetReason(status);
            return;
        }

        OnStatusSelected?.Invoke(status, null);
    }

    private void GetReason(SecurityStatus status)
    {
        if (_reasonDialog != null)
        {
            _reasonDialog.MoveToFront();
            _suppressStatusEvent = true;
            StatusOption.SelectId((int) _currentStatus);
            _suppressStatusEvent = false;
            return;
        }

        var field = "reason";
        var title = Loc.GetString("criminal-records-status-" + status.ToString().ToLower());
        var placeholders = _proto.Index(ReasonPlaceholders);
        var placeholder = Loc.GetString("criminal-records-console-reason-placeholder",
            ("placeholder", _random.Pick(placeholders)));
        var prompt = Loc.GetString("criminal-records-console-reason");
        var entry = new QuickDialogEntry(field, QuickDialogEntryType.LongText, prompt, placeholder);
        var entries = new List<QuickDialogEntry> { entry };
        _reasonDialog = new DialogWindow(title, entries);

        var confirmed = false;
        _reasonDialog.OnConfirmed += responses =>
        {
            var reason = responses[field];
            if (reason.Length < 1 || reason.Length > _maxLength)
                return;

            confirmed = true;
            OnStatusSelected?.Invoke(status, reason);
        };

        _reasonDialog.OnClose += () =>
        {
            _reasonDialog = null;
            if (confirmed)
                return;

            _suppressStatusEvent = true;
            StatusOption.SelectId((int) _currentStatus);
            _suppressStatusEvent = false;
        };
    }

    private void UpdateStatusIcon(SecurityStatus status)
    {
        var state = status switch
        {
            SecurityStatus.Paroled => "hud_paroled",
            SecurityStatus.Wanted => "hud_wanted",
            SecurityStatus.Detained => "hud_incarcerated",
            SecurityStatus.Discharged => "hud_discharged",
            SecurityStatus.Suspected => "hud_suspected",
            SecurityStatus.Hostile => "hud_hostile",
            SecurityStatus.Eliminated => "hud_eliminated",
            _ => null
        };

        if (state == null)
        {
            StatusIcon.Visible = false;
            return;
        }

        StatusIcon.Visible = true;
        var specifier = new SpriteSpecifier.Rsi(new ResPath("/Textures/Interface/Misc/security_icons.rsi"), state);
        StatusIcon.SetFromSpriteSpecifier(specifier);
        StatusIcon.DisplayRect.TextureScale = new Vector2(2f, 2f);
    }

    private void UpdateReasonLabel(SecurityStatus status, string? reason)
    {
        if (reason == null)
        {
            StatusReason.Visible = false;
            return;
        }

        var message = FormattedMessage.FromMarkupOrThrow(
            status == SecurityStatus.Suspected
                ? Loc.GetString("criminal-records-console-suspected-reason")
                : Loc.GetString("criminal-records-console-wanted-reason"));
        message.AddText($": {reason}");
        StatusReason.SetMessage(message);
        StatusReason.Visible = true;
    }
}
