using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.Stylesheets.Palette;
using Content.Shared.Atmos;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.Damage.Systems;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Content.Shared.Mobs.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
namespace Content.Client.HealthAnalyzer.UI;

// Health analyzer UI is split from its window because it's used by both the
// health analyzer item and the cryo pod UI.

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private const float StatusColorTransitionDuration = 0.18f;

    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly DamageableSystem _damageable;
    private readonly MobThresholdSystem _mobThresholds;
    private readonly Dictionary<Label, StatusColorTransition> _statusColorTransitions = new();
    private readonly List<Label> _completedColorTransitions = new();

    public bool IsScanActive { get; private set; }
    public MobState PatientState { get; private set; } = MobState.Invalid;

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
        _damageable = _entityManager.System<DamageableSystem>();
        _mobThresholds = _entityManager.System<MobThresholdSystem>();
        InitializeSections(); // FIsh edit - независимое сворачивание разделов
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);

        if (target == null
            || !_entityManager.TryGetComponent<DamageableComponent>(target, out var damageable))
        {
            IsScanActive = false;
            BeginDamageComparison(null, false); // FIsh edit - сброс истории без пациента
            PatientState = MobState.Invalid;
            NoPatientDataPanel.Visible = true;
            PatientDataContainer.Visible = false;
            AlertsContainer.Visible = false;
            DamageContainer.Visible = false;
            // FIsh edit - не оставляем подсказки и показания реагентов без данных о пациенте
            TreatmentContainer.Visible = false;
            ReagentsContainer.Visible = false;
            return;
        }

        NoPatientDataPanel.Visible = false;
        PatientDataContainer.Visible = true;
        DamageContainer.Visible = true;
        // FIsh edit - показываем помощник и реагенты только при наличии данных о пациенте
        TreatmentContainer.Visible = true;
        ReagentsContainer.Visible = true;

        IsScanActive = state.ScanMode == true;
        BeginDamageComparison(target, IsScanActive); // FIsh edit - сравнение только замеров одного пациента

        // Scan Mode

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        SetStatusStyle(
            ScanModeLabel,
            state.ScanMode == true
                ? StyleClass.StatusGood
                : StyleClass.LabelWeak);

        // Patient Information

        SpriteView.SetEntity(target.Value);
        SpriteView.Visible = state.ScanMode.HasValue && state.ScanMode.Value;
        NoDataTex.Visible = !SpriteView.Visible;

        NameLabel.Text = _entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidProfileComponent>(target.Value,
                out var humanoidComponent)
                ? Loc.GetString(_prototypes.Index(humanoidComponent.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        // Basic Diagnostic

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
        SetTemperatureStyle(state.Temperature);

        BloodLabel.Text = !float.IsNaN(state.BloodLevel)
            ? $"{state.BloodLevel * 100:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
        SetPercentageStyle(BloodLabel, state.BloodLevel * 100f);

        // Sunrise-Edit start - hunger and thirst label updates
        HungerLabel.Text = state.HungerLevel.HasValue && !float.IsNaN(state.HungerLevel.Value)
            ? $"{state.HungerLevel.Value:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
        SetPercentageStyle(HungerLabel, state.HungerLevel);

        ThirstLabel.Text = state.ThirstLevel.HasValue && !float.IsNaN(state.ThirstLevel.Value)
            ? $"{state.ThirstLevel.Value:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
        SetPercentageStyle(ThirstLabel, state.ThirstLevel);
        // Sunrise-Edit end

        var mobState = _entityManager.TryGetComponent<MobStateComponent>(target.Value, out var mobStateComponent)
            ? mobStateComponent.CurrentState
            : MobState.Invalid;

        PatientState = mobState;

        StatusLabel.Text = GetStatus(mobState);
        SetStatusStyle(StatusLabel, mobState switch
        {
            MobState.Alive => StyleClass.StatusGood,
            MobState.Critical => StyleClass.StatusWarning,
            MobState.Dead => StyleClass.StatusCritical,
            _ => StyleClass.LabelWeak,
        });

        // Total Damage

        var totalDamage = _damageable.GetTotalDamage((target.Value, damageable));
        DamageLabel.Text = totalDamage.ToString();
        UpdateDamageTrend(DamageTrendLabel, totalDamage - _previousTotalDamage); // FIsh edit
        SetDamageStyle(totalDamage, mobState);

        // Alerts

        var showAlerts = state.Unrevivable == true || state.Bleeding == true;

        AlertsContainer.Visible = showAlerts;

        if (showAlerts)
            AlertsListContainer.RemoveAllChildren();

        if (state.Unrevivable == true)
            AlertsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Margin = new Thickness(0, 4),
                HorizontalExpand = true,
            });

        if (state.Bleeding == true)
            AlertsListContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-bleeding-text"),
                Margin = new Thickness(0, 4),
                HorizontalExpand = true,
            });

        // Damage Groups

        var damageSortedGroups =
            _damageable.GetDamagePerGroup(target.Value)
                .OrderByDescending(damage => damage.Value)
                .ToDictionary(x => x.Key, x => x.Value);

        var damagePerType = _damageable.GetAllDamage(target.Value).DamageDict;

        DrawDiagnosticGroups(damageSortedGroups, damagePerType);

        // FIsh edit start - помощник лечения и реагенты находятся после списка повреждений
        DrawTreatmentAssistant(
            target.Value,
            mobState,
            totalDamage,
            damageSortedGroups,
            damagePerType,
            state);
        DrawReagents(state.Reagents);
        SaveDamageComparison(totalDamage, damageSortedGroups, damagePerType);
        // FIsh edit end
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    private void SetTemperatureStyle(float temperature)
    {
        if (float.IsNaN(temperature))
        {
            SetStatusStyle(TemperatureLabel, StyleClass.LabelWeak);
            return;
        }

        var celsius = temperature - Atmospherics.T0C;
        var style = celsius switch
        {
            < 25f or > 45f => StyleClass.StatusCritical,
            < 35f or > 39f => StyleClass.StatusWarning,
            _ => StyleClass.StatusGood,
        };
        SetStatusStyle(TemperatureLabel, style);
    }

    private void SetPercentageStyle(Label label, float? percentage)
    {
        if (!percentage.HasValue || float.IsNaN(percentage.Value))
        {
            SetStatusStyle(label, StyleClass.LabelWeak);
            return;
        }

        var style = percentage.Value switch
        {
            < 25f => StyleClass.StatusCritical,
            < 50f => StyleClass.StatusBad,
            < 75f => StyleClass.StatusWarning,
            _ => StyleClass.StatusGood,
        };
        SetStatusStyle(label, style);
    }

    private void SetDamageStyle(FixedPoint2 totalDamage, MobState mobState)
    {
        var style = mobState switch
        {
            MobState.Dead => StyleClass.StatusCritical,
            MobState.Critical => StyleClass.StatusBad,
            _ when totalDamage <= 0 => StyleClass.StatusGood,
            _ when totalDamage < 25 => StyleClass.StatusOkay,
            _ when totalDamage < 50 => StyleClass.StatusWarning,
            _ => StyleClass.StatusBad,
        };
        SetStatusStyle(DamageLabel, style);
    }

    private void SetStatusStyle(Label label, string style)
    {
        label.RemoveStyleClass(StyleClass.StatusGood);
        label.RemoveStyleClass(StyleClass.StatusOkay);
        label.RemoveStyleClass(StyleClass.StatusWarning);
        label.RemoveStyleClass(StyleClass.StatusBad);
        label.RemoveStyleClass(StyleClass.StatusCritical);
        label.RemoveStyleClass(StyleClass.LabelWeak);
        label.AddStyleClass(style);

        var targetColor = IsScanActive
            ? GetStatusColor(style)
            : HealthAnalyzerSheetlet.InactiveTextColor;
        if (!label.FontColorOverride.HasValue)
        {
            label.FontColorOverride = targetColor;
            return;
        }

        if (_statusColorTransitions.TryGetValue(label, out var currentTransition)
            && currentTransition.Target == targetColor)
        {
            return;
        }

        var currentColor = label.FontColorOverride.Value;
        if (currentColor == targetColor)
        {
            _statusColorTransitions.Remove(label);
            return;
        }

        _statusColorTransitions[label] = new StatusColorTransition(currentColor, targetColor);
    }

    // FIsh edit start - плавная смена цветов основных показателей
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _completedColorTransitions.Clear();
        foreach (var (label, transition) in _statusColorTransitions)
        {
            transition.Elapsed += args.DeltaSeconds;
            var progress = Math.Clamp(transition.Elapsed / StatusColorTransitionDuration, 0f, 1f);
            var easedProgress = 1f - MathF.Pow(1f - progress, 3f);
            label.FontColorOverride = Color.InterpolateBetween(
                transition.Start,
                transition.Target,
                easedProgress);

            if (progress >= 1f)
                _completedColorTransitions.Add(label);
        }

        foreach (var label in _completedColorTransitions)
            _statusColorTransitions.Remove(label);
    }

    private static Color GetStatusColor(string style)
    {
        return style switch
        {
            StyleClass.StatusGood => Palettes.Status.Good,
            StyleClass.StatusOkay => Palettes.Status.Okay,
            StyleClass.StatusWarning => Palettes.Status.Warning,
            StyleClass.StatusBad => Palettes.Status.Bad,
            StyleClass.StatusCritical => Palettes.Status.Critical,
            _ => Color.DarkGray,
        };
    }

    private sealed class StatusColorTransition(Color start, Color target)
    {
        public readonly Color Start = start;
        public readonly Color Target = target;
        public float Elapsed;
    }
    // FIsh edit end

    // FIsh edit start - список посторонних реагентов в кровотоке
    private void DrawReagents(IReadOnlyList<ReagentQuantity> reagents)
    {
        ReagentsListContainer.RemoveAllChildren();

        if (reagents.Count == 0)
        {
            ReagentsListContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-reagents-none"),
                StyleClasses = { "LabelSubText" },
            });
            return;
        }

        var entries = new List<(ReagentPrototype Prototype, FixedPoint2 Quantity)>();

        foreach (var reagent in reagents)
        {
            if (_prototypes.TryIndex<ReagentPrototype>(reagent.Reagent.Prototype, out var prototype))
                entries.Add((prototype, reagent.Quantity));
        }

        entries.Sort((left, right) => string.Compare(
            left.Prototype.LocalizedName,
            right.Prototype.LocalizedName,
            StringComparison.CurrentCulture));

        foreach (var (prototype, quantity) in entries)
        {
            var message = new FormattedMessage();
            message.PushColor(prototype.SubstanceColor);
            message.AddText("● ");
            message.Pop();
            message.AddText(prototype.LocalizedName);

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };
            var label = new RichTextLabel
            {
                HorizontalExpand = true,
            };
            label.SetMessage(message);
            row.AddChild(label);
            row.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-reagents-amount", ("amount", quantity)),
                HorizontalAlignment = HAlignment.Right,
                StyleClasses = { HealthAnalyzerSheetlet.ReagentAmount },
            });
            ReagentsListContainer.AddChild(row);
        }
    }
    // FIsh edit end

    private void DrawDiagnosticGroups(
        Dictionary<ProtoId<DamageGroupPrototype>, FixedPoint2> groups,
        IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        foreach (var (damageGroupId, damageAmount) in groups)
        {
            if (damageAmount == 0 && (!_canCompareDamage || _previousDamageGroups.GetValueOrDefault(damageGroupId) == 0)) // FIsh edit
                continue;

            var groupTitleText = $"{Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                ("amount", damageAmount)
            )}";

            var groupPanel = new PanelContainer
            {
                Margin = new Thickness(0, 3, 0, 0),
                StyleClasses = { HealthAnalyzerSheetlet.DamageGroup },
            };
            var groupContainer = new BoxContainer
            {
                Align = AlignMode.Begin,
                Orientation = LayoutOrientation.Vertical,
                Margin = new Thickness(7, 4),
            };

            // FIsh edit start - изменение группы относительно предыдущего замера
            var groupTitle = CreateDiagnosticGroupTitle(groupTitleText, damageGroupId);
            AddDamageTrend(groupTitle, damageAmount - _previousDamageGroups.GetValueOrDefault(damageGroupId));
            groupContainer.AddChild(groupTitle);
            // FIsh edit end
            groupPanel.AddChild(groupContainer);
            GroupsContainer.AddChild(groupPanel);

            // Show the damage for each type in that group.
            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

            foreach (var type in group.DamageTypes)
            {
                var typeAmount = damageDict.GetValueOrDefault(type); // FIsh edit
                if (typeAmount <= 0 && (!_canCompareDamage || _previousDamageTypes.GetValueOrDefault(type) <= 0)) // FIsh edit
                    continue;

                var damageString = Loc.GetString(
                    "health-analyzer-window-damage-type-text",
                    ("damageType", _prototypes.Index<DamageTypePrototype>(type).LocalizedName),
                    ("amount", typeAmount)
                );

                var label = CreateDiagnosticItemLabel(damageString.Insert(0, "· "));
                label.StyleClasses.Add(HealthAnalyzerSheetlet.DamageType);
                // FIsh edit start - отдельная стрелка для типа повреждений
                var row = new BoxContainer { Margin = new Thickness(34, 0, 0, 1) };
                label.HorizontalExpand = true;
                label.ClipText = true;
                row.AddChild(label);
                AddDamageTrend(row, typeAmount - _previousDamageTypes.GetValueOrDefault(type));
                groupContainer.AddChild(row);
                // FIsh edit end
            }
        }
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private static Label CreateDiagnosticItemLabel(string text)
    {
        return new Label
        {
            Text = text,
        };
    }

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower())
        });

        // FIsh edit start - оставляем место для стрелки при узком окне
        var title = CreateDiagnosticItemLabel(text);
        title.HorizontalExpand = true;
        title.ClipText = true;
        title.ToolTip = text;
        rootContainer.AddChild(title);
        // FIsh edit end

        return rootContainer;
    }
}
