using Content.Client.Stylesheets;
using Content.Client.Stylesheets.Palette;
using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Timing;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    private const string FadeInAnimationKey = "health-analyzer-fade-in";
    private const float FadeInDuration = 0.16f;
    private const float ThemeTransitionDuration = 0.3f;

    private HealthAnalyzerTheme _theme = HealthAnalyzerTheme.Active;
    private ColorPalette _displayPalette = HealthAnalyzerSheetlet.GetPalette(HealthAnalyzerTheme.Active);
    private ColorPalette _startPalette = HealthAnalyzerSheetlet.GetPalette(HealthAnalyzerTheme.Active);
    private ColorPalette _targetPalette = HealthAnalyzerSheetlet.GetPalette(HealthAnalyzerTheme.Active);
    private float _themeElapsed = ThemeTransitionDuration;

    private static readonly Animation FadeInAnimation = new()
    {
        Length = TimeSpan.FromSeconds(FadeInDuration),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Modulate),
                InterpolationMode = AnimationInterpolationMode.Cubic,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(Color.White.WithAlpha(0f), 0f),
                    new AnimationTrackProperty.KeyFrame(Color.White, FadeInDuration),
                },
            },
        },
    };

    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        // FIsh edit start - слои интерфейса растягиваются вместе с окном
        LayoutContainer.SetAnchorPreset(AnalyzerScroll, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(EffectsLayer, LayoutContainer.LayoutPreset.Wide);
        // FIsh edit end
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        HealthAnalyzer.Populate(msg.State);

        // FIsh edit - эффект запускается только после получения свежих данных
        SetTheme(HealthAnalyzer.IsScanActive, HealthAnalyzer.PatientState);
        EffectsLayer.SetScanActive(HealthAnalyzer.IsScanActive);
        if (HealthAnalyzer.IsScanActive)
            EffectsLayer.TriggerScan();
    }

    // FIsh edit start - плавная смена палитры самого интерфейса
    private void SetTheme(bool scanActive, MobState patientState)
    {
        var theme = !scanActive
            ? HealthAnalyzerTheme.Inactive
            : patientState switch
            {
                MobState.Critical => HealthAnalyzerTheme.Critical,
                MobState.Dead => HealthAnalyzerTheme.Dead,
                _ => HealthAnalyzerTheme.Active,
            };

        if (_theme != theme)
        {
            _theme = theme;
            _startPalette = _displayPalette;
            _targetPalette = HealthAnalyzerSheetlet.GetPalette(theme);
            _themeElapsed = 0f;
        }

        ApplyPalette(this, _displayPalette, theme == HealthAnalyzerTheme.Inactive);
        EffectsLayer.SetAccentColor(_displayPalette.Base);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_themeElapsed >= ThemeTransitionDuration)
            return;

        _themeElapsed = Math.Min(ThemeTransitionDuration, _themeElapsed + args.DeltaSeconds);
        var progress = _themeElapsed / ThemeTransitionDuration;
        var easedProgress = progress * progress * (3f - 2f * progress);
        _displayPalette = InterpolatePalette(_startPalette, _targetPalette, easedProgress);
        ApplyPalette(this, _displayPalette, _theme == HealthAnalyzerTheme.Inactive);
        EffectsLayer.SetAccentColor(_displayPalette.Base);
    }

    private static void ApplyPalette(Control control, ColorPalette palette, bool inactive)
    {
        if (control is PanelContainer panel &&
            HealthAnalyzerSheetlet.CreateThemedPanel(panel, palette) is { } style)
        {
            panel.PanelOverride = style;
        }

        if (control is Label label && (inactive || !HasSemanticStatus(label)))
        {
            label.FontColorOverride = label.HasStyleClass(HealthAnalyzerSheetlet.MetricKey) ||
                                      label.HasStyleClass(HealthAnalyzerSheetlet.DamageType) ||
                                      label.HasStyleClass(StyleClass.LabelSubText)
                ? palette.TextDark
                : palette.Text;
        }

        foreach (var child in control.Children)
            ApplyPalette(child, palette, inactive);
    }

    private static bool HasSemanticStatus(Label label)
    {
        return label.HasStyleClass(StyleClass.StatusGood) ||
               label.HasStyleClass(StyleClass.StatusOkay) ||
               label.HasStyleClass(StyleClass.StatusWarning) ||
               label.HasStyleClass(StyleClass.StatusBad) ||
               label.HasStyleClass(StyleClass.StatusCritical);
    }

    private static ColorPalette InterpolatePalette(ColorPalette source, ColorPalette target, float amount)
    {
        return source with
        {
            Base = Color.InterpolateBetween(source.Base, target.Base, amount),
            Element = Color.InterpolateBetween(source.Element, target.Element, amount),
            Background = Color.InterpolateBetween(source.Background, target.Background, amount),
            BackgroundLight = Color.InterpolateBetween(source.BackgroundLight, target.BackgroundLight, amount),
            BackgroundDark = Color.InterpolateBetween(source.BackgroundDark, target.BackgroundDark, amount),
            Text = Color.InterpolateBetween(source.Text, target.Text, amount),
            TextDark = Color.InterpolateBetween(source.TextDark, target.TextDark, amount),
        };
    }
    // FIsh edit end

    // FIsh edit start - плавное открытие окна
    protected override void Opened()
    {
        base.Opened();

        if (HasRunningAnimation(FadeInAnimationKey))
            StopAnimation(FadeInAnimationKey);

        Modulate = Color.White.WithAlpha(0f);
        PlayAnimation(FadeInAnimation, FadeInAnimationKey);
    }
    // FIsh edit end
}
