using Content.Client.UserInterface.Controls;
using Content.Shared._Fish.PerformanceGuardian;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Fish.PerformanceGuardian;

[GenerateTypedNameReferences]
public sealed partial class PerformanceGuardianWindow : FancyWindow
{
    private readonly List<PgLazyTab> _tabs = new();
    private int _selected;

    public event Action<PgSnapshotSection>? TabNeedsData;
    public PgSnapshotSection CurrentSection { get; private set; } = PgSnapshotSection.Dashboard;

    public PerformanceGuardianWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AddTab(PgSnapshotSection.Dashboard, "pg-tab-dashboard", PgSnapshotFormat.Dashboard);
        AddTab(PgSnapshotSection.Performance, "pg-tab-performance", PgSnapshotFormat.Performance);
        AddTab(PgSnapshotSection.Players, "pg-tab-players", PgSnapshotFormat.Players);
        AddTab(PgSnapshotSection.Risk, "pg-tab-risk", PgSnapshotFormat.Risk);
        AddTab(PgSnapshotSection.Timeline, "pg-tab-timeline", PgSnapshotFormat.Timeline);
        AddTab(PgSnapshotSection.HeatMap, "pg-tab-heatmap", PgSnapshotFormat.HeatMap);
        AddTab(PgSnapshotSection.TopEntities, "pg-tab-top-entities", PgSnapshotFormat.TopEntities);
        AddTab(PgSnapshotSection.TopSystems, "pg-tab-top-systems", PgSnapshotFormat.TopSystems);
        AddTab(PgSnapshotSection.Alerts, "pg-tab-alerts", PgSnapshotFormat.Alerts);
        AddTab(PgSnapshotSection.Reports, "pg-tab-reports", PgSnapshotFormat.Reports);
        AddTab(PgSnapshotSection.Profiler, "pg-tab-profiler", PgSnapshotFormat.Profiler);
        AddTab(PgSnapshotSection.History, "pg-tab-history", PgSnapshotFormat.History);

        Tabs.OnTabChanged += OnTabChanged;
        CurrentSection = PgSnapshotSection.Dashboard;
    }

    private void AddTab(PgSnapshotSection section, string locKey, Func<PgServerSnapshot, string> formatter)
    {
        var tab = new PgLazyTab(section, formatter);
        tab.SetPlaceholder(Loc.GetString("pg-tab-waiting"));
        Tabs.AddChild(tab);
        Tabs.SetTabTitle(_tabs.Count, Loc.GetString(locKey));
        _tabs.Add(tab);
    }

    private void OnTabChanged(int index)
    {
        _selected = index;
        if ((uint)index >= (uint)_tabs.Count)
            return;

        CurrentSection = _tabs[index].Section;
        TabNeedsData?.Invoke(CurrentSection);
    }

    public void ApplySnapshot(PgSnapshotSection section, PgServerSnapshot snapshot)
    {
        StatusLabel.Text = Loc.GetString("pg-window-status-ok",
            ("load", snapshot.LoadLevel.ToString()),
            ("risk", snapshot.RiskScore.ToString("0.0")),
            ("tps", snapshot.Tps.ToString("0.0")));

        // Apply to matching tab; All updates every tab (rare).
        for (var i = 0; i < _tabs.Count; i++)
        {
            var tab = _tabs[i];
            if (section == PgSnapshotSection.All || section == tab.Section ||
                (section == PgSnapshotSection.Dashboard && i == _selected))
            {
                // Only paint selected tab unless All.
                if (section != PgSnapshotSection.All && i != _selected && tab.Section != section)
                    continue;
            }

            if (section == PgSnapshotSection.All || tab.Section == section ||
                (i == _selected && (section == PgSnapshotSection.All || section == tab.Section)))
            {
                if (i == _selected || section == PgSnapshotSection.All)
                    tab.Apply(snapshot);
            }
        }

        // Ensure selected tab always refreshes on any snapshot that includes its data.
        if ((uint)_selected < (uint)_tabs.Count)
        {
            var selected = _tabs[_selected];
            if (section == PgSnapshotSection.All || section == selected.Section)
                selected.Apply(snapshot);
        }
    }

    public void ShowAlert(PgAlert alert)
    {
        StatusLabel.Text = Loc.GetString("pg-window-status-alert",
            ("severity", alert.Severity.ToString()),
            ("title", alert.Title));
    }
}
