using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Fish.PerformanceGuardian;

/// <summary>
/// Thin F7 host tab that opens/focuses Performance Guardian.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PerformanceGuardianLauncherTab : Control
{
    public PerformanceGuardianLauncherTab()
    {
        RobustXamlLoader.Load(this);
        OpenButton.OnPressed += _ =>
        {
            var controller = UserInterfaceManager.GetUIController<PerformanceGuardianUIController>();
            controller.OpenWindow();
        };
    }
}
