using Content.Client._Starlight;
using Content.Client._Starlight.Medical.Surgery;
using Content.Client.UserInterface.Controls;
using Content.Shared.Body;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Localization;
using Robust.Shared.Timing;

namespace Content.Client._Fish.Medical.Surgery;

/// <summary>Pairs an anatomical selector with the existing surgery and step controls.</summary>
[GenerateTypedNameReferences]
public sealed partial class FishSurgeryWindow : FancyWindow
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private const string FadeAnimationKey = "fish-surgery-fade";
    private static readonly Animation WindowFade = CreateFade(0f, 0.22f);
    private static readonly Animation SectionFade = CreateFade(0.55f, 0.18f);
    private static readonly Animation StepTransition = CreateColorTransition(FishSurgerySheetlet.Palette.Element, 0.35f);

    /// <summary>Requests a part's operations without performing a surgical step.</summary>
    public event Action<EntityUid>? PartSelected;

    /// <summary>Refreshes conditions periodically while the window is open.</summary>
    public event Action? RefreshRequested;

    /// <summary>Updates the displayed server-backed action progress each frame.</summary>
    public event Action? ProgressRequested;

    private float _refreshElapsed;
    private string? _partName;
    private string? _operationName;
    private EntityUid? _step;
    private bool _showingSteps;
    private readonly Dictionary<SurgeryStepButton, (bool Current, bool Completed)> _stepStates = new();
    private readonly Dictionary<SurgeryStepButton, ProgressBar> _stepProgress = new();
    private ProgressBar? _activeProgress;
    private Action? _confirmAction;
    private readonly List<EntityUid> _additionalParts = new();
    private readonly List<(EntityUid Part, string Name)> _shownParts = new();
    private readonly Dictionary<RichTextLabel, string?> _shownText = new();
    private (EntityUid? Part, bool ChoosingPart, bool ShowingSteps)? _selection;

    public FishSurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        BodyDiagram.PartSelected += part => PartSelected?.Invoke(part);
        BodyDiagram.HoveredPartChanged += name => SetLabelText(HoverName, name ?? _loc.GetString("fish-surgery-hover-hint"));
        CancelAction.OnPressed += _ => DismissConfirmation();
        ConfirmAction.OnPressed += _ => ConfirmPendingAction();
        AdditionalParts.OnItemSelected += args =>
        {
            if (args.Id >= 0 && args.Id < _additionalParts.Count)
                PartSelected?.Invoke(_additionalParts[args.Id]);
        };
    }

    /// <summary>Updates the patient heading and its full-name tooltip.</summary>
    public void SetPatient(string name, EntityUid? patient = null)
    {
        SetLabelText(PatientName, name);
        PatientName.ToolTip = name;
        BodyDiagram.Patient = patient;
        BodyDiagram.RefreshAppearance();
    }

    /// <summary>Clears the diagram before the BUI rebuilds its list of parts.</summary>
    public void ClearParts()
    {
        _shownParts.Clear();
        BodyDiagram.ClearParts();
        _additionalParts.Clear();
        AdditionalParts.Clear();
        AdditionalParts.Visible = false;
    }

    /// <summary>Reconciles anatomy without resetting hover, selection or unchanged dropdown entries.</summary>
    public void SetParts(IReadOnlyList<(Entity<OrganComponent> Part, string Name)> parts)
    {
        var changed = parts.Count != _shownParts.Count;
        for (var i = 0; !changed && i < parts.Count; i++)
            changed = _shownParts[i] != (parts[i].Part.Owner, parts[i].Name);
        if (!changed)
            return;

        _shownParts.Clear();
        _additionalParts.Clear();
        AdditionalParts.Clear();
        AdditionalParts.Visible = false;
        BodyDiagram.BeginPartsUpdate();
        foreach (var (part, name) in parts)
        {
            _shownParts.Add((part, name));
            AddPart(part, name);
        }
        BodyDiagram.EndPartsUpdate();
    }

    /// <summary>
    /// Uses the diagram for standard anatomy, with a compact selector only for unmapped extra parts.
    /// </summary>
    public void AddPart(Entity<OrganComponent> part, string name)
    {
        if (BodyDiagram.AddPart(part, name))
            return;
        AdditionalParts.AddItem(name, _additionalParts.Count);
        _additionalParts.Add(part);
        AdditionalParts.Visible = true;
    }

    /// <summary>Synchronizes the diagram highlight and stage heading with BUI navigation.</summary>
    public void ShowSelection(EntityUid? part, string? name, bool choosingPart, bool showingSteps)
    {
        BodyDiagram.SelectedPart = part;
        AreaHeader.Visible = !choosingPart;
        _showingSteps = showingSteps;
        var selection = (part, choosingPart, showingSteps);
        if (_selection != selection)
        {
            DismissConfirmation();
            _selection = selection;
            if (IsOpen)
            {
                StartFade(AreaHeader, SectionFade, 0.55f);
                StartFade(showingSteps ? Steps : Surgeries, SectionFade, 0.55f);
            }
        }
        _partName = name;
        UpdateAreaHeading();
        EmptySelection.Visible = choosingPart;
        NoOperations.Visible = !choosingPart && !showingSteps && Surgeries.ChildCount == 0;
        SetLabelText(StageTitle, _loc.GetString(showingSteps ? "fish-surgery-steps" : "fish-surgery-operations"));
        SetButtonText(PartsButton, _loc.GetString("fish-surgery-clear-selection"));
        PartsButton.Visible = !choosingPart && !showingSteps;
        SetButtonText(SurgeriesButton, _loc.GetString("fish-surgery-back-operations"));
        SetButtonText(StepsButton, _loc.GetString("fish-surgery-back-prerequisite"));
        SurgeriesButton.Visible = showingSteps;
        StepsButton.Visible = showingSteps && !StepsButton.Disabled;
    }

    /// <summary>Updates the compact operation heading and invalidates confirmation when the step changes.</summary>
    public void SetOperation(string? operation, EntityUid? step = null)
    {
        if (_operationName != operation || _step != step)
            DismissConfirmation();

        if (_operationName != operation && _showingSteps && IsOpen)
            StartFade(Steps, SectionFade, 0.55f);
        _operationName = operation;
        _step = step;
        UpdateAreaHeading();
    }

    /// <summary>Показывает активные состояния области компактными текстовыми статусами.</summary>
    public void SetAreaStatus(bool incision, bool retracted)
    {
        IncisionStatus.Visible = incision;
        RetractionStatus.Visible = retracted;
    }

    private void UpdateAreaHeading()
    {
        var title = _partName ?? _loc.GetString("fish-surgery-select-part");
        if (_operationName != null && _showingSteps)
            title = _loc.GetString("fish-surgery-context", ("part", title), ("operation", _operationName));
        SetOptionalText(SelectedPart, title);
        SelectedPart.ToolTip = title;
    }

    /// <summary>Clears row animation state before changing operations.</summary>
    public void ResetStepHistory()
    {
        DismissConfirmation();
        _stepStates.Clear();
        _stepProgress.Clear();
        _activeProgress = null;
    }

    /// <summary>Сохраняет завершённый этап до выбора другой операции.</summary>
    public bool KeepStepCompleted(SurgeryStepButton step, bool completed)
        => completed || _stepStates.TryGetValue(step, out var previous) && previous.Completed;

    /// <summary>Animates actual step transitions without hiding rows or changing their layout.</summary>
    public void SetStepPresentation(SurgeryStepButton step, bool current, bool completed)
    {
        var state = (current, completed);
        if (_stepStates.TryGetValue(step, out var previous) && previous != state && IsOpen)
        {
            step.StopAnimation(FadeAnimationKey);
            step.Modulate = FishSurgerySheetlet.Palette.Element;
            step.PlayAnimation(StepTransition, FadeAnimationKey);
        }
        _stepStates[step] = state;
    }

    /// <summary>Добавляет полосу прогресса внутрь этапа, не меняя расположение строки.</summary>
    public void RegisterStep(SurgeryStepButton step)
    {
        var progress = new ProgressBar
        {
            Name = "FishSurgeryStepProgress",
            MinHeight = 3,
            MaxHeight = 3,
            MinValue = 0,
            MaxValue = 1,
            Value = 0,
            Visible = false,
            HorizontalAlignment = HAlignment.Stretch,
            VerticalAlignment = VAlignment.Bottom,
            MouseFilter = MouseFilterMode.Ignore,
        };
        progress.AddStyleClass("FishSurgeryProgress");
        step.Button.AddChild(progress);
        _stepProgress[step] = progress;
    }

    /// <summary>Обновляет полосу прогресса выполняемого этапа.</summary>
    public void SetActionProgress(EntityUid? step, string caption, float progress, bool warning = false)
    {
        if (!TryGetStepProgress(step ?? _step, out var bar))
        {
            ClearActionProgress();
            return;
        }

        if (_activeProgress != bar)
        {
            if (_activeProgress != null)
                _activeProgress.Visible = false;
            _activeProgress = bar;
        }

        bar.Visible = true;
        bar.ToolTip = caption;
        bar.Value = Math.Clamp(progress, 0f, 1f);
        if (warning == bar.HasStyleClass("FishSurgeryProgressDanger"))
            return;
        if (warning)
            bar.AddStyleClass("FishSurgeryProgressDanger");
        else
            bar.RemoveStyleClass("FishSurgeryProgressDanger");
    }

    /// <summary>Обновляет прогресс без перезаписи подсказки и перестроения строки.</summary>
    public void SetActionFraction(EntityUid? step, float progress)
    {
        if (TryGetStepProgress(step ?? _step, out var bar) && bar == _activeProgress)
            bar.Value = Math.Clamp(progress, 0f, 1f);
    }

    public void ClearActionProgress()
    {
        if (_activeProgress != null)
            _activeProgress.Visible = false;
        _activeProgress = null;
    }

    /// <summary>Размещает подтверждение необратимого действия сразу под его этапом.</summary>
    public void RequestConfirmation(EntityUid step, string description, Action confirmed)
    {
        if (!TryGetStepButton(step, out var row))
            return;

        _confirmAction = confirmed;
        ConfirmationText.SetMessage(description);
        ConfirmationPanel.Orphan();
        Steps.AddChild(ConfirmationPanel);
        ConfirmationPanel.SetPositionInParent(row.GetPositionInParent() + 1);
        ConfirmationPanel.Visible = true;
    }

    /// <summary>Invalidates confirmation when selection or action context changes.</summary>
    public void DismissConfirmation()
    {
        _confirmAction = null;
        ConfirmationPanel.Visible = false;
        if (ConfirmationPanel.Parent != ConfirmationParking)
        {
            ConfirmationPanel.Orphan();
            ConfirmationParking.AddChild(ConfirmationPanel);
        }
    }

    internal void ConfirmPendingAction()
    {
        var action = _confirmAction;
        DismissConfirmation();
        action?.Invoke();
    }

    /// <summary>Applies consistent spacing, icon sizing and wrapping to the upstream choice controls.</summary>
    public static void ConfigureChoice(ChoiceControl choice)
    {
        choice.Button.RemoveStyleClass("ButtonSquare");
        choice.Button.AddStyleClass("FishSurgeryButton");
        choice.Button.MinHeight = 38;
        choice.Texture.SetSize = new(24, 24);
        choice.Texture.Stretch = TextureRect.StretchMode.KeepAspectCentered;
        choice.NameLabel.HorizontalExpand = true;
    }

    private bool TryGetStepButton(EntityUid? step, out SurgeryStepButton button)
    {
        SurgeryStepButton? fallback = null;
        foreach (var candidate in _stepProgress.Keys)
        {
            if (candidate.Step != step)
                continue;
            if (_stepStates.TryGetValue(candidate, out var state) && state.Current)
            {
                button = candidate;
                return true;
            }
            fallback ??= candidate;
        }

        button = fallback!;
        return fallback != null;
    }

    private bool TryGetStepProgress(EntityUid? step, out ProgressBar progress)
    {
        if (TryGetStepButton(step, out var button))
            return _stepProgress.TryGetValue(button, out progress!);
        progress = null!;
        return false;
    }

    protected override void Opened()
    {
        base.Opened();
        StartFade(this, WindowFade, 0f);
    }

    private static Animation CreateFade(float initialAlpha, float duration)
        => CreateColorTransition(Color.White.WithAlpha(initialAlpha), duration);

    private static Animation CreateColorTransition(Color initialColor, float duration)
    {
        return new Animation
        {
            Length = TimeSpan.FromSeconds(duration),
            AnimationTracks =
            {
                new AnimationTrackControlProperty
                {
                    Property = nameof(Modulate),
                    InterpolationMode = AnimationInterpolationMode.Cubic,
                    KeyFrames =
                    {
                        new AnimationTrackProperty.KeyFrame(initialColor, 0f),
                        new AnimationTrackProperty.KeyFrame(Color.White, duration),
                    },
                },
            },
        };
    }

    private static void StartFade(Control control, Animation animation, float initialAlpha)
    {
        control.StopAnimation(FadeAnimationKey);
        control.Modulate = Color.White.WithAlpha(initialAlpha);
        control.PlayAnimation(animation, FadeAnimationKey);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (!IsOpen)
            return;

        ProgressRequested?.Invoke();
        _refreshElapsed += args.DeltaSeconds;
        if (_refreshElapsed < 0.2f)
            return;

        _refreshElapsed = 0f;
        BodyDiagram.RefreshAppearance();
        RefreshRequested?.Invoke();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _confirmAction = null;
            RefreshRequested = null;
            ProgressRequested = null;
            _stepStates.Clear();
            _stepProgress.Clear();
            _activeProgress = null;
        }

        base.Dispose(disposing);
    }

    // Label.Text и смена стилевых классов в Robust инвалидируют разметку даже при одинаковых значениях.
    private static void SetLabelText(Label label, string text)
    {
        if (label.Text != text)
            label.Text = text;
    }

    private static void SetButtonText(Button button, string text)
    {
        if (button.Text != text)
            button.Text = text;
    }

    private void SetOptionalText(RichTextLabel label, string? text)
    {
        if (_shownText.TryGetValue(label, out var previous) && previous == text)
            return;
        _shownText[label] = text;
        label.Visible = !string.IsNullOrEmpty(text);
        if (text != null)
            label.SetMessage(text);
    }
}
