using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Fragments;
using Content.Shared._Fish.Mechs;
using Content.Shared._Fish.Mechs.Components;
using Content.Shared.Mech.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mech.Ui;

[GenerateTypedNameReferences]
public sealed partial class MechMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _ent = default!;

    private EntityUid _mech;

    public event Action<EntityUid>? OnRemoveButtonPressed;

    public MechMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetEntity(EntityUid uid)
    {
        MechView.SetEntity(uid);
        _mech = uid;
    }

    public void UpdateMechStats()
    {
        if (!_ent.TryGetComponent<MechComponent>(_mech, out var mechComp))
            return;

        var integrityPercent = (mechComp.MaxIntegrity - mechComp.Integrity) / mechComp.MaxIntegrity;
        IntegrityDisplayBar.Value = integrityPercent.Float();
        IntegrityDisplay.Text = Loc.GetString("mech-integrity-display", ("amount", (integrityPercent*100).Int()));

        if (mechComp.MaxEnergy != 0f)
        {
            var energyPercent = mechComp.Energy / mechComp.MaxEnergy;
            EnergyDisplayBar.Value = energyPercent.Float();
            EnergyDisplay.Text = Loc.GetString("mech-energy-display", ("amount", (energyPercent*100).Int()));
        }
        else
        {
            EnergyDisplayBar.Value = 0f;
            EnergyDisplay.Text = Loc.GetString("mech-energy-missing");
        }

        SlotDisplay.Text = Loc.GetString("mech-slot-display",
            ("amount", mechComp.MaxEquipmentAmount - mechComp.EquipmentContainer.ContainedEntities.Count));

        // Fish edit start - статус internal damage / modes
        UpdateFishStatus();
        // Fish edit end
    }

    private void UpdateFishStatus()
    {
        var sb = new StringBuilder();

        if (_ent.TryGetComponent(_mech, out MechInternalDamageComponent? internalDamage) &&
            internalDamage.Damage != MechInternalDamageFlags.None)
        {
            sb.Append(Loc.GetString("mech-ui-internal-damage", ("flags", internalDamage.Damage.ToString())));
        }

        if (_ent.TryGetComponent(_mech, out MechOverloadComponent? overload) && overload.Active)
            AppendStatus(sb, Loc.GetString("mech-ui-overload-active"));

        if (_ent.TryGetComponent(_mech, out MechDefenceModeComponent? defence) && defence.Active)
            AppendStatus(sb, Loc.GetString("mech-ui-defence-active"));

        if (_ent.TryGetComponent(_mech, out MechThrustersComponent? thrusters) && thrusters.Active)
            AppendStatus(sb, Loc.GetString("mech-ui-thrusters-active"));

        if (_ent.TryGetComponent(_mech, out MechStrafeComponent? strafe) && strafe.Active)
            AppendStatus(sb, Loc.GetString("mech-ui-strafe-active"));

        if (_ent.TryGetComponent(_mech, out MechDnaLockComponent? dna) && dna.Enabled)
            AppendStatus(sb, Loc.GetString("mech-ui-dna-locked"));

        if (_ent.TryGetComponent(_mech, out MechMaintenanceComponent? maint) &&
            maint.State != MechMaintenanceState.Ready)
            AppendStatus(sb, Loc.GetString("mech-ui-maintenance", ("state", maint.State.ToString())));

        if (_ent.TryGetComponent(_mech, out MechCabinAtmosComponent? cabin))
            AppendStatus(sb, Loc.GetString(cabin.UseInternalTank ? "mech-ui-internals-on" : "mech-ui-internals-off"));

        if (_ent.TryGetComponent(_mech, out MechZoomComponent? zoom) && zoom.Active)
            AppendStatus(sb, Loc.GetString("mech-ui-zoom-active"));

        if (_ent.TryGetComponent(_mech, out MechPhasingComponent? phasing) && phasing.Active)
            AppendStatus(sb, Loc.GetString("mech-ui-phasing-active"));

        FishStatusDisplay.Text = sb.Length > 0 ? sb.ToString() : Loc.GetString("mech-ui-status-ok");
    }

    private static void AppendStatus(StringBuilder sb, string line)
    {
        if (sb.Length > 0)
            sb.Append('\n');
        sb.Append(line);
    }

    public void UpdateEquipmentView()
    {
        if (!_ent.TryGetComponent<MechComponent>(_mech, out var mechComp))
            return;

        EquipmentControlContainer.Children.Clear();
        foreach (var ent in mechComp.EquipmentContainer.ContainedEntities)
        {
            if (!_ent.TryGetComponent<MetaDataComponent>(ent, out var metaData))
                continue;

            var uicomp = _ent.GetComponentOrNull<UIFragmentComponent>(ent);
            var ui = uicomp?.Ui?.GetUIFragmentRoot();

            var control = new MechEquipmentControl(ent, metaData.EntityName, ui);

            control.OnRemoveButtonPressed += () => OnRemoveButtonPressed?.Invoke(ent);

            EquipmentControlContainer.AddChild(control);
        }
    }
}
