- type: department # Fish-Blueshield
  id: BlueShield
  name: department-Blueshield
  description: department-Blueshield-description
  color: "#0f4e81"
  roles:
   - BlueShieldEnsign
   - BlueShieldOfficer
  #  - BlueShieldOperative
  primary: false
  weight: 50
