- type: department # Fish-Blueshield
  id: BlueShield
  name: department-Blueshield
  description: department-Blueshield-description
  color: "#0f4e81"
  roles:
   - BlueShieldEnsign
   - BlueShieldOfficer
   - RepresentativeBlueShield
  #  - BlueShieldOperative
  primary: false
  weight: 60


- type: department
  id: SpecialOperationsAlt
  name: department-SpecialOperations
  description: department-SpecialOperations-description
  color: "#0c344d"
  roles:
   - SpecOpsOfficer #Fish-edit
  weight: 57

- type: department
  id: Court
  name: department-Court
  description: department-Court-description
  color: "#0c344d"
  roles:
   - Magistrat
   - CentcommSectoralJudge
  weight: 55

- type: department
  id: Law
  name: department-Law
  description: department-Law-description
  color: "#FF5297"
  roles:
   - OversightOfficer
   - IAA
   - Lawyer
   - NtrOfficer
  weight: 52
