using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Fish.Research;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Fish.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class DestructiveAnalyzerMenu : FancyWindow
{
    public event Action? OnServerPressed;
    public event Action? OnAnalyzePressed;
    public event Action? OnEjectPressed;

    public DestructiveAnalyzerMenu()
    {
        RobustXamlLoader.Load(this);

        ServerButton.OnPressed += _ => OnServerPressed?.Invoke();
        AnalyzeButton.OnPressed += _ => OnAnalyzePressed?.Invoke();
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
    }

    public void Update(DestructiveAnalyzerBoundUserInterfaceState state)
    {
        PointsLabel.SetMarkup(Loc.GetString("destructive-analyzer-menu-points", ("points", state.ServerPoints)));

        if (!state.ConnectedToServer)
            StatusLabel.SetMarkup(Loc.GetString("destructive-analyzer-menu-status-offline"));
        else if (state.IsAnalyzing)
            StatusLabel.SetMarkup(Loc.GetString("destructive-analyzer-menu-status-analyzing"));
        else
            StatusLabel.SetMarkup(Loc.GetString("destructive-analyzer-menu-status-ready"));

        if (!state.HasItem)
        {
            ItemLabel.SetMarkup(Loc.GetString("destructive-analyzer-menu-item-empty"));
            ValueLabel.SetMarkup(Loc.GetString("destructive-analyzer-menu-value-none"));
        }
        else
        {
            ItemLabel.SetMarkup(Loc.GetString("destructive-analyzer-menu-item", ("item", state.ItemName ?? "?")));
            if (state.ResearchValue > 0)
                ValueLabel.SetMarkup(Loc.GetString("destructive-analyzer-menu-value", ("points", state.ResearchValue)));
            else
                ValueLabel.SetMarkup(Loc.GetString("destructive-analyzer-menu-value-invalid"));
        }

        AnalyzeButton.Disabled = !state.CanAnalyze;
        EjectButton.Disabled = !state.HasItem || state.IsAnalyzing;
    }
}
