- type: job
  id: JobGhostWMBase
  name: pw-roles-shared-jobghostbase-name
  description: pw-roles-shared-jobghostbase-desc
  playTimeTracker: OverAllGhostWMBase
  setPreference: false
  weight: 10
  jobEntity: MobObserver
  icon: "JobIconPassenger"
  canBeAntag: false
  access:
  - AssCoreBase
  - AssArmBase
  alwaysUseSpawner: true


#Job
